insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('0','Bardo','El Guardián Herrante',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('1','Annie','Hija de la Oscuridad',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('2','Olaf','El Berserker',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('3','Galio','La Tristeza del Guardián',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('4','Twisted Fate','El Maestro de las Cartas',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('5','Xin Zhao','El Senescal de Demacia',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('6','Urgot','El Orgullo del Verdugo',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('7','LeBlanc','La Embaucadora',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('8','Vladimir','El Sesgador Carmesí',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('9','Fiddlesticks','El Mensajero de la Muerte',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('10','Kayle','La Justiciera',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('11','Maestro Yi','El Espadachín Wuju',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('12','Alistar','El Minotauro',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('13','Ryze','El Hechicero Rebelde',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('14','Sion','El Coloso No Muerto',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('15','Sivir','Señora de la Batalla',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('16','Soraka','La Hija de las Estrellas',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('17','Teemo','El Explorador Veloz',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('18','Tristana','La Artillera Megling',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('19','Warwick','El Cazador Sangriento',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('20','Nunu','El Jinete de Yetis',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('21','Miss Fortune','La Cazarrecompensas',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('22','Ashe','La Arquera de Hielo',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('23','Tryndamere','El Rey Bárbaro',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('24','Jax','Maestro de Armas',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('25','Morgana','Ángel Caído',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('26','Zilean','El Guardián del Tiempo',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('27','Signed','El Químico Loco',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('28','Evelyn','Hacedora de Viudas',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('29','Twitch','La Rata Apestada',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('30','Karthus','La Voz de la Muerte',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('31','Cho\'Gath','El Terror del Vacío',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('32','Amumu','La Momia Triste',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('33','Rammus','El Armadurillo',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('34','Anivia','La Criofénix',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('35','Shaco','El Bufón Siniestro',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('36','Dr. Mundo','El Loco de Zaun',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('37','Sona','Virtuosa de las Cuerdas',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('38','Kassadin','El Caminante del Vacío',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('39','Irelia','La Voluntad de las Cuchillas',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('40','Janna','La Furia de la Tormenta',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('41','Gangplank','El Azote de los Mares',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('42','Corki','El Bombardero Osado',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('43','Karma','La Iluminada',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('44','Taric','El Caballero Gema',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('45','Veigar','El Pequeño Maestro del Mal',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('48','Trundle','El Rey Troll',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('50','Swain','El Maestro Estratega',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('51','Caitlyn','La Sheriff de Piltover',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('53','Blitzcrank','El Gran Gólem de Vapor',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('54','Malphite','Fragmento del Monolito',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('55','Katarina','La Cuchilla Siniestra',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('56','Nocturne','La Pesadilla Eterna',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('57','Maokai','El Treant Retorcido',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('58','Renekton','Carnicero de las Arenas',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('59','Jarvan IV','El Ejemplo de Demacia',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('60','Elise','La Reina de las Arañas',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('61','Oriana','La Dama Mecánica',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('62','Wukong','El Rey de los Monos',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('63','Brand','La Venganza Ardiente',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('64','Lee Sin','El Monje Ciego',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('67','Vayne','La Cazadora Noctívaga',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('68','Rumble','La Amenaza Mecánica',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('69','Cassiopeia','El Abrazo de la Serpiente',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('72','Skarner','La Vanguardia de Cristal',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('74','Heimerdinger','El Inventor Venerado',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('75','Nasus','El Guardián de las Arenas',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('76','Nidalee','La Cazadora Bestial',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('77','Udyr','El Caminante Espiritual',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('78','Poppy','La Embajadora de Hierro',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('79','Gragas','El Camorrista',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('80','Phanteon','El Artesano de la Guerra',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('81','Ezreal','El Explorador Pródigo',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('82','Mordekaiser','El Maestro del Metal',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('83','Yorick','El Sepulturero',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('84','Akali','El Puño de la Sombra',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('85','Kennen','El Corazón de la Tempestad',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('86','Garen','El Poder de Demacia',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('89','Leona','Amanecer Radiante',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('90','Malzahar','El Profeta del Vacío',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('91','Talon','La Sombra de la Espada',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('92','Riven','La Desterrada',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('96','Kog\'Maw','La Boca del Abismo',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('98','Shen','Ojo del Crepúsculo',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('99','Lux','La Dama Luminosa',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('101','Xerath','El Mago Ascendente',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('102','Shyvana','La Medio Dragón',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('103','Ahri','La Mujer Zorro de Nueve Colas',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('104','Graves','El Forajido',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('105','Fizz','El Gamberro de las Mareas',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('106','Volibear','El Rugir del Trueno',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('107','Rengar','Acechador Orgulloso',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('110','Varus','La Flecha del Castigo',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('111','Nautilus','El Titán Abisal',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('112','Viktor','El Heraldo de las Máquinas',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('113','Sejuani','La Cólera del Invierno',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('114','Fiora','Estocada Excelsa',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('115','Ziggs','El Experto en Hexplosivos',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('117','Lulu','El Hada Hechicera',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('119','Draven','El Ejecutor Glorioso',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('120','Hecarim','La Sombra de la Guerra',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('121','Kha\'Zix','El Saqueador del Vacío',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('122','Darius','La Mano de Noxus',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('126','Jayce','El Defensor del Mañana',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('127','Lissandra','La Bruja de Hielo',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('131','Diana','Desdén de la Luna',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('133','Quinn','Las Alas de Demacia',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('134','Syndra','La Soberana Oscura',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('143','Zyra','Dama de Espinas',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('150','Gnar','El Eslabón Perdido',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('154','Zac','El Arma Secreta',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('157','Yasuo','La Espada sin Honor',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('161','Vel\'Koz','El Ojo del Vacío',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('201','Braum','El Corazón de Freljord',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('222','Jinx','La Bala Perdida',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('236','Lucian','Destello Purificador',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('238','Zed','El Maestro de las Sombras',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('254','Vi','Agente de Piltover',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('266','Aatrox','La Espada de los Oscuros',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('267','Nami','La Invocadora de Mareas',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('268','Azir','El Emperador de las Arenas',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('412','Thresh','El Carcelero Implacable',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('429','Kalista','El Espíritu de la Venganza',NULL);
insert into `champs` (`IDchmp`, `NMchmp`, `TTLchmp`, `CHdate`) values('421','Rek\'Sai','La Amenaza Subterránea','2014-12-11');
